### ISSUE TITLE
Messages sometimes out of order in Colloquy 2.4

### ISSUE THREAD

**Issue by JohnAlbin** [JohnAlbin/succinct-for-colloquy#2]
Colloquy 2.4 (build 5334) works fine, but Colloquy 2.4 (build 5336) sometimes displays messages out of order. Especially messages that are directed to the current user.

**Comment by JohnAlbin** [comment]
There was something buggy somewhere in the old main.xsl file that caused messages to be lost when converted to HTML. I didn't want to debug it, so instead the main.xsl has been completely been rewritten. I started with Colloquy's default.xsl and modified slightly to get what we want.

Haven't experienced the bug since the rewrite.

/me crosses fingers.

**Comment by aseba** [comment]
This is happening to me in Colloquy 2.4 with a recently cloned version of succinct

**Comment by JohnAlbin** [comment]
Yeah, actually, I just experienced it again yesterday too. I wonder if this is a bug in Colloquy 2.4 itself and its handling of theme's that use the "consecutive insert" mode.

I may be able to work around the bug though.

BTW, a temporary workaround is to type `/reload style` whenever you experience that bug. It will reload the chat stream into the theme and it always corrects the display error for me.

**Comment by aseba** [comment]
Yes, I've just learned that command thanks to @fjcero. Great theme nevertheless!

**Comment by JohnAlbin** [comment]
So I'm pretty sure this is a bug in Colloquy itself. It just handles "consecutive insert" mode differently then it used to. And I cannot figure out how to prevent this problem.

The work-around is to not use that mode. That's the fix I'm trying now.
